### ISSUE TITLE
SonarQubeExtension not able to start: The process cannot access the file settings.cfg

### ISSUE THREAD

**Issue by aamarber** [jmecosta/VSSonarQubeExtension#94]
I think this is a minor and not really important bug, because first I can't reproduce it and I think it's a weird combination:

1. I opened VS.
2. As it was being too slow to open, I clicked once again to open it and then at the first window of VS it shows the next error (the other VS opened without problems):

SonarQubeExtension not able to start: The process cannot access the file 'C:\Users\amartin\AppData\Roaming\VSSonarExtension\settings.cfg' because it is being used by another process.

 at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path)
   at ExtensionHelpers.ConfigurationHelper.WriteOptionInApplicationData(String pluginKey, String key, String value)
   at VSSonarExtensionUi.ViewModel.Configuration.GeneralConfigurationViewModel.OnExtensionDebugModeEnabledChanged()
   at VSSonarExtensionUi.ViewModel.Configuration.GeneralConfigurationViewModel.set_ExtensionDebugModeEnabled(Boolean value)
   at VSSonarExtensionUi.ViewModel.Configuration.GeneralConfigurationViewModel.ResetDefaults()
   at VSSonarExtensionUi.ViewModel.Configuration.GeneralConfigurationViewModel..ctor(VSonarQubeOptionsViewModel viewModel, ISonarRestService restService, IVsEnvironmentHelper helper, SonarQubeViewModel sonarQubeViewModel, IConfigurationHelper configurationHelper)
   at VSSonarExtensionUi.ViewModel.Configuration.VSonarQubeOptionsViewModel.InitModels()
   at VSSonarExtensionUi.ViewModel.Configuration.VSonarQubeOptionsViewModel..ctor(PluginController plugincontroller, SonarQubeViewModel model, IVsEnvironmentHelper vsHelper, IConfigurationHelper configurationHelper)
   at VSSonarExtensionUi.ViewModel.SonarQubeViewModel.InitOptionsModel()
   at VSSonarExtensionUi.ViewModel.SonarQubeViewModel..ctor()
   at VSSonarQubeExtension.SonarQubeViewModelFactory.get_SQViewModel()
   at VSSonarQubeExtension.Helpers.VsEvents..ctor(IVsEnvironmentHelper environment, DTE2 dte2, VsSonarExtensionPackage vsSonarExtensionPackage)
   at VSSonarQubeExtension.VsSonarExtensionPackage.Initialize()

**Comment by jmecosta** [comment]
ok thanks for reporting... i will fix this for the next release

**Comment by jmecosta** [comment]
@aamarber can you check with this: https://github.com/jmecosta/VSSonarQubeExtension/releases/tag/4.0.0-Beta-1 perhapps now its fixed
